[keyboard]
name = "RMK 4x7 Split"
product_name = "RMK 4x7 Split"
manufacturer = "haobo"
vendor_id = 0x4C4B
product_id = 0x4643
chip = "nrf52840"

[layout]
rows = 4
cols = 7
layers = 1
keymap = [
  [ "Kc00", "Kc01", "Kc02", "Kc03", "Kc04", "Kc05", "Kc06" ],
  [ "Kc10", "Kc11", "Kc12", "Kc13", "Kc14", "Kc15", "Kc16" ],
  [ "Kc20", "Kc21", "Kc22", "Kc23", "Kc24", "Kc25", "Kc26" ],
  [ "Kc30", "Kc31", "Kc32", "Kc33", "Kc34", "Kc35", "Kc36" ]
]

[storage]

[ble]
enabled = true

[split]
connection = "ble"

[split.central]
rows = 4
cols = 7
# Kairė pusė (master)
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]
matrix_type = "normal"
row_pins = ["P0_02", "P0_03", "P0_04", "P0_05"]
col_pins = ["P0_06", "P0_07", "P0_08", "P0_09", "P0_10", "P0_11", "P0_12"]

[[split.peripheral]]
rows = 4
cols = 7
# Dešinė pusė (slave)
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]
matrix_type = "normal"
row_pins = ["P1_02", "P1_03", "P1_04", "P1_05"]
col_pins = ["P1_06", "P1_07", "P1_08", "P1_09", "P1_10", "P1_11", "P1_12"]
