[keyboard]
name = "MySplitBT"
product_name = "MySplitBT"
vendor_id = 0x4C4B
product_id = 0x4643
manufacturer = "haobo"
chip = "nrf52840"

[layout]
rows = 4
cols = 7
layers = 1
keymap = [
  ["Kc00","Kc01","Kc02","Kc03","Kc04","Kc05","Kc06"],
  ["Kc10","Kc11","Kc12","Kc13","Kc14","Kc15","Kc16"],
  ["Kc20","Kc21","Kc22","Kc23","Kc24","Kc25","Kc26"],
  ["Kc30","Kc31","Kc32","Kc33","Kc34","Kc35","Kc36"]
]

[ble]
enabled = true

[vial]
enabled = true

[split]
connection = "ble"

[split.central]  # master kairė pusė
rows = 4
cols = 7
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xE2, 0x21, 0x80, 0xC0, 0xC7]

[split.central.matrix]
matrix_type = "normal"
row_pins = ["P0_06", "P0_08", "P0_17", "P0_20"]
col_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06", "P0_31"]

[[split.peripheral]]  # slave dešinė pusė
rows = 4
cols = 7
row_offset = 0
col_offset = 0
ble_addr = [0x7E, 0xFE, 0x73, 0x9E, 0x66, 0xE3]

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P1_02", "P1_03", "P1_04", "P1_05"]
col_pins = ["P1_06", "P1_07", "P1_08", "P1_09", "P1_10", "P1_11", "P1_12"]
